//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodiSoft_task_Gapunich
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptions
    {
        public int Id { get; set; }
        public string Desciption_Restoran { get; set; }
    }
}
